spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
greeting-service:
  greeting: "Atualizando configurações sem interromper o serviço"
  default-value: "Word"